YAGUARETE_KAA_SA/eCommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from sitio.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("sitio.urls")),
    path('sitio/', include("sitio.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('registrarse/', include('USUARIOS.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

YAGUARETE_KAA_SA/sitio/urls.py
from django.urls import path, include
from . import views
from eCommerce.urls import path, include




app_name = "sitio"
urlpatterns = [
    path('', views.index, name="index"),
    
    path('filtro_secciones/<int:seccion_id>', views.filtro_secciones, name="filtro_secciones"),
    path('<int:articulo_id>', views.articulo, name="articulo"),
    path('articulo_alta', views.articulo_alta, name="articulo_alta"),
    path('articulo_editar/<int:articulo_id>', views.articulo_editar, name="articulo_editar"),
    path('articulo_eliminar/<int:articulo_id>', views.articulo_eliminar, name="articulo_eliminar"),
    path('leer_mas_tarde/<int:articulo_id>', views.leer_mas_tarde, name="leer_mas_tarde"),
    
    path('pantallaDeAcercaDe', views.pantallaDeAcercaDe, name="pantallaDeAcercaDe"),
    path('carrito', views.carrito, name="carrito"),
    path('resultadoBusqueda', views.resultadoBusqueda, name="resultadoDeBusqueda"),
    path('registro.html', views.registro, name="registro"),
    
    #path('filtro_categorias/<int:categoria_id>', views.filtro_categorias, name="filtro_categorias"),
    #path('<int:producto_id>', views.producto, name="producto"),
    #path('producto_alta', views.producto_alta, name="producto_alta"),
    #path('producto_editar/<int:producto_id>', views.producto_editar, name="producto_editar"),
    #path('producto_eliminar/<int:producto_id>', views.producto_eliminar, name="producto_eliminar"),
    #path('ver_mas_tarde/<int:producto_id>', views.ver_mas_tarde, name="ver_mas_tarde"),
]

YAGUARETE_KAA_SA/sitio/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Seccion(models.Model):
    descripcion = models.CharField(max_length=64, null=False)

    def __str__(self):
        return f"{self.descripcion}"

class Articulo(models.Model):
    seccion = models.ForeignKey(Seccion, on_delete=models.CASCADE, related_name="clasificacion_seccion")
    fecha_publicacion = models.DateField(null= False)
    titulo = models.CharField(max_length=250, null=False)
    contenido = models.CharField(max_length=2000, null=False)
    imagen = models.FileField(upload_to='imagenes/')
    publicador = models.ForeignKey(User, on_delete=models.CASCADE, related_name="publicador")

    def __str__(self):
        return f"{self.fecha_publicacion} - {self.titulo} ({self.publicador})"

#class resultadoDeBusqueda(models,Model):
#    titulo = models.ForeignKey(Articulo, relate_name="usuario")
#    def 

class LeerMasTarde(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name="usuario")
    publicaciones = models.ManyToManyField(Articulo)

    def __str__(self):
        return f"{self.usuario} - {self.publicaciones}"
#___________________________________________________________________________________________________
#Producto
#class Categoria(models.Model):
#    descripcion = models.CharField(max_length=64, null=False)
#
#    def __str__(self):
#        return f"{self.descripcion}"
#
#class Producto(models.Model):
#    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, related_name="clasificacion_seccion")
#    precio = models.IntegerField()
#    nombre = models.CharField(max_length=250, null=False)
#    descripcion = models.CharField(max_length=2000, null=False)
#    imagen = models.FileField(upload_to='imagenes/')
#    moderador = models.ForeignKey(User, on_delete=models.CASCADE, related_name="moderador")
#
#    def __str__(self):
#        return f"{self.nombre} - {self.precio} ({self.imagen})"
#
#class VerMasTarde(models.Model):
#    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name="usuario")
#    publicaciones = models.ManyToManyField(Producto)
#
#    def __str__(self):
#        return f"{self.usuario} - {self.publicaciones}"

YAGUARETE_KAA_SA/sitio/forms.py
from django import forms
#from .models import Producto
from .models import Articulo

class FormArticulo(forms.ModelForm):

    #campos del modelo
    class Meta:
        model = Articulo
        fields = ('seccion', 'fecha_publicacion', 'titulo', 'contenido', 'imagen')
        widgets = {
            'fecha_publicacion': forms.SelectDateWidget(attrs={'class': 'pub_fecha_publicacion'}),
            'titulo': forms.TextInput(attrs={'class': 'pub_titulo'}),
            'contenido': forms.Textarea(attrs={'class': 'pub_contenido'}),
            'imagen': forms.FileInput(attrs={'name':'imagen_adjunta', 'class': 'pub_imagen'}),
            
        }
#___________________________________________________________________________________________________
#Producto
#class FormProducto(forms.ModelForm):
#
#    #campos del modelo
#    class Meta:
#        model = Producto
#        fields = ('categoria', 'precio', 'nombre', 'descripcion', 'imagen')
#        widgets = {
#            'precio': forms.TextInput(attrs={'class': 'pub_precio'}),
#            'nombre': forms.TextInput(attrs={'class': 'pub_nombre'}),
#            'descripcion': forms.Textarea(attrs={'class': 'pub_descripcion'}),
#            'imagen': forms.FileInput(attrs={'name':'imagen_adjunta', 'class': 'pub_imagen'}),
#        }

YAGUARETE_KAA_SA/sitio/views.py
from django.contrib.auth.models import User
from django.http.response import HttpResponseRedirect
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from .forms import *
#from .models import Categoria, Producto
from .models import Articulo, Seccion
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required  
from eCommerce import urls
from sitio import urls
# from django.contrib.auth.decorators import permission_required

# Create your views here.

def index(request):
    if "leer_mas_tarde" not in request.session:
        request.session["leer_mas_tarde"] = []
    return render(request,"eCommerce/index.html", {
        "lista_articulos": Articulo.objects.all(),
        "lista_secciones": Seccion.objects.all(),
        "leer_mas_tarde": request.session["leer_mas_tarde"],
    })
#_____________________________________________________________
#def index(request):
#    if "ver_mas_tarde" not in request.session:
#        request.session["ver_mas_tarde"] = []
#    return render(request,"eCommerce/index.html", {
#        "lista_productos": Producto.objects.all(),
#        "lista_categorias": Categoria.objects.all(),
#        "ver_mas_tarde": request.session["ver_mas_tarde"],
#    })


def pantallaDeAcercaDe(request):
    return render(request,"pantallaDeAcercaDe.html")


        
def carrito(request):
    return render(request,"carrito.html")

def registro(request):
    return render(request, "eCommerce/registro.html")

def articulo(request, articulo_id):
    un_articulo = get_object_or_404(Articulo, id=articulo_id)
    return render(request, "eCommerce/articulo.html", {
        "articulo": un_articulo
    })
#_____________________________________________________________
#def producto(request, producto_id):
#    un_producto = get_object_or_404(Producto, id=producto_id)
#    return render(request, "eCommerce/producto.html", {
#        "producto": un_producto
#    })

def articulo_alta(request):
    if request.method == "POST":
        user = User.objects.get(username=request.user)
        form = FormArticulo(request.POST, request.FILES, instance=Articulo(imagen=request.FILES['imagen'], publicador=user))      
        if form.is_valid():
            form.save()
            return redirect("sitio:index")          
    else:
        form = FormArticulo(initial={'fecha_publicacion':timezone.now()})
        return render(request, "eCommerce/articulo_nuevo.html", {
            "form": form
        })
#_____________________________________________________________
#def producto_alta(request):
#    if request.method == "POST":
#        user = User.objects.get(username=request.user)
#        form = FormProducto(request.POST, request.FILES, instance=Producto(imagen=request.FILES['imagen'], publicador=user))      
#        if form.is_valid():
#            form.save()
#            return redirect("sitio:index")          
#    else:
#        form = FormProducto(initial={'fecha_registro':timezone.now()})
#        return render(request, "eCommerce/producto_nuevo.html", {
#            "form": form
#        })


def articulo_editar(request, articulo_id):
    un_articulo = get_object_or_404(Articulo, id=articulo_id)
    if request.method == "POST":  
        user = User.objects.get(username=request.user)   
        un_articulo.publicador = user
        form = FormArticulo(data=request.POST, files=request.FILES, instance=un_articulo)
        if form.is_valid():
            form.save()
            return redirect("sitio:index")
    else:
        form = FormArticulo(instance = un_articulo)
        return render(request, 'eCommerce/articulo_edicion.html', {
            "articulo": un_articulo,
            "form": form
        })
#_________________________________________________________________
#def producto_editar(request, producto_id):
#    un_producto = get_object_or_404(Producto, id=producto_id)
#    if request.method == "POST":  
#        user = User.objects.get(username=request.user)   
#        un_producto.moderador = user
#        form = FormProducto(data=request.POST, files=request.FILES, instance=un_producto)
#        if form.is_valid():
#            form.save()
#            return redirect("sitio:index")
#    else:
#        form = FormProducto(instance = un_producto)
#        return render(request, 'eCommerce/producto_edicion.html', {
#            "producto": un_producto,
#            "form": form
#       })



def articulo_eliminar(request, articulo_id):
    un_articulo = get_object_or_404(Articulo, id=articulo_id)
    un_articulo.delete()
    return redirect("sitio:index")
#_________________________________________________________________
#def producto_eliminar(request, articulo_id):
#    un_producto = get_object_or_404(Producto, id=articulo_id)
#    un_producto.delete()
#    return redirect("sitio:index")

def filtro_secciones(request, seccion_id):
    una_seccion = get_object_or_404(Seccion, id=seccion_id)
    queryset = Articulo.objects.all()
    queryset = queryset.filter(seccion=una_seccion)
    return render(request,"eCommerce/index.html", {
        "lista_articulos": queryset,
        "lista_secciones": Seccion.objects.all(),
        "seccion_seleccionada": una_seccion
    })

def filtro_articulos(request, articulo_id):
     if request.method == "POST":  
        return print(articulo_id)

def resultadoBusqueda(request):
    return render(request,"resultadoDeBusqueda.html")

#_________________________________________________________________
#def filtro_categorias(request, seccion_id):
#    una_categoria = get_object_or_404(Categoria, id=seccion_id)
#    queryset = Categoria.objects.all()
#    queryset = queryset.filter(categoria=una_categoria)
#    return render(request,"eCommerce/index.html", {
#        "lista_productos": queryset,
#        "lista_categorias": Categoria.objects.all(),
#        "categoria_seleccionada": una_categoria
#    })



@login_required
def leer_mas_tarde(request, articulo_id):
    un_articulo = get_object_or_404(Articulo, id=articulo_id)
    for id in request.session["leer_mas_tarde"]:
        if id == articulo_id:
            #existe el articulo
            return HttpResponseRedirect(reverse("sitio:articulo", args=(un_articulo.id,)))            
    request.session["leer_mas_tarde"] += [articulo_id]
    return HttpResponseRedirect(reverse("sitio:articulo", args=(un_articulo.id,)))   



#___________________________________________________________________________________________________
#Producto

#@login_required
#def ver_mas_tarde(request, producto_id):
#    un_producto = get_object_or_404(Producto, id=producto_id)
#    for id in request.session["ver_mas_tarde"]:
#        if id == producto_id:
#            #existe el producto
#            return HttpResponseRedirect(reverse("sitio:producto", args=(un_producto.id,)))            
#    request.session["ver_mas_tarde"] += [producto_id]
#    return HttpResponseRedirect(reverse("sitio:producto", args=(un_producto.id,)))   

YAGUARETE_KAA_SA/sitio/templates/eCommerce/articulo.html
{% extends "eCommerce/layout.html" %}
{% block content %}
<h2>{{ articulo.titulo }}</h2>
<div class="alert alert-info" role="alert"></div>
<div class="alert alert-info" role="alert">{{ articulo.seccion }}</div>
<p><span class="publicacion_fecha" >{{ articulo.fecha_publicacion }}</span></p>
<a href="{% url 'sitio:leer_mas_tarde' articulo.id %}">Agregar al Carrito</a>
<p><img src="{{ media_url  }}{{ articulo.imagen.url }}" alt="{{ articulo.imagen.name }}" /></p>
<h3>Contenido:</h3>
<p id="contenido">{{ articulo.contenido |safe }}</p>
<p>Publicado por <span class="badge badge-secondary">{{ articulo.publicador }}</span></p>
<a href="{% url 'sitio:index'%}">Volver</a>
{% endblock %}

YAGUARETE_KAA_SA/sitio/templates/eCommerce/articulo_edicion.html
{% extends "eCommerce/layout.html" %}
{% block content %}
<h3>Publicar un Articulo</h3>
{% if user.is_authenticated %}
<div class="alert alert-info" role="alert"></div>
<form enctype="multipart/form-data" action="{% url 'sitio:articulo_editar' articulo.id %}" method="post" >
    {% csrf_token %}
    <div class="form-group row">
        <label for="seccion_input"  class="col-sm-2 col-form-label">Seccion:</label> {{ form.seccion }} {{ form.seccion.errors }}
    </div>
    <div class="form-group row">
        <label for="titulo_input"  class="col-sm-2 col-form-label">Titulo:</label> {{ form.titulo }} {{ form.titulo.errors }}
    </div>
    <div class="form-group row">
        <label for="publicacion_input"  class="col-sm-2 col-form-label">Fecha de Publicacion:</label> {{ form.fecha_publicacion }} {{ form.fecha_publicacion.errors }}
    </div>
    <div class="form-group row">
        <label for="imagen_input"  class="col-sm-2 col-form-label">Imagen Adjunta:</label> {{ form.imagen }} {{ form.imagen.errors }}
    </div>
    <div class="form-group row"  class="col-sm-2 col-form-label">
        <label for="contenido_input">Contenido:</label> {{ form.contenido }} {{ form.contenido.errors }}
        <script>$("#id_contenido").removeAttr("required");</script>
    </div>
    <div class="col-auto">
        <a class="btn btn-secondary" href="{% url 'sitio:index'%}">Volver</a>
        <input type="submit" class="btn btn-primary" value="Editar">
    </div>
</form>
<a href="{% url 'sitio:index'%}">Volver</a>
{% else %} 

{% endif %} 

{% endblock %}

YAGUARETE_KAA_SA/sitio/templates/eCommerce/articulo_nuevo.html
{% extends "eCommerce/layout.html" %}
{% block content %}
<h3>Dar de Alta un Producto</h3>
{% if user.is_authenticated %}
<div class="alert alert-info" role="alert"></div>
<form enctype="multipart/form-data" action="{% url 'sitio:articulo_alta' %}" method="post" >
    {% csrf_token %}
    <div class="form-group row">
        <label for="seccion_input"  class="col-sm-2 col-form-label">Seccion:</label> {{ form.seccion }} {{ form.seccion.errors }}
    </div>
    <div class="form-group row">
        <label for="titulo_input"  class="col-sm-2 col-form-label">Titulo:</label> {{ form.titulo }} {{ form.titulo.errors }}
    </div>
    <div class="form-group row">
        <label for="publicacion_input"  class="col-sm-2 col-form-label">Fecha de Alta:</label> {{ form.fecha_publicacion }} {{ form.fecha_publicacion.errors }}
    </div>
    <div class="form-group row">
        <label for="imagen_input"  class="col-sm-2 col-form-label">Imagen Adjunta:</label> {{ form.imagen }} {{ form.imagen.errors }}
    </div>
    <div class="form-group row"  class="col-sm-2 col-form-label">
        <label for="contenido_input">Contenido:</label><br> {{ form.contenido }} {{ form.contenido.errors }}
        <script>$("#id_contenido").removeAttr("required");</script>
    </div>
    <div class="col-auto">
        <a class="btn btn-secondary" type="button" href="{% url 'sitio:index'%}">Volver</a>
        <input type="submit" class="btn btn-primary" value="Publicar">
    </div>
</form>
{% else %} 

{% endif %} 

{% endblock %}

YAGUARETE_KAA_SA/sitio/templates/eCommerce/index.html
{% extends "eCommerce/layout.html" %}
{% block content %}
    <h2>Productos</h2>
    {% if seccion_seleccionada %}
        <div class="alert alert-info" role="alert">{{ seccion_seleccionada }}</div>
    {% else %}
        <div class="alert alert-info" role="alert">Todos los Productos</div>
    {% endif %}
    <ul>
        {% for un_articulo in lista_articulos %}
            <li>              
                <a href="{% url 'sitio:articulo' un_articulo.id %}">Ver #{{un_articulo.id}}</a>                
                {% if perms.sitio.change_articulo %}
                <a href="{% url 'sitio:articulo_editar' un_articulo.id %}">Modificar</a>  
                {% endif %}
                {% if perms.sitio.delete_articulo %} 
                <a href="{% url 'sitio:articulo_eliminar' un_articulo.id %}">Eliminar</a>  
                {% endif %}
                --- {{un_articulo}}
            </li>
        {% empty %}
            <li>No hay Productos para mostrar.</li>
        {% endfor %}
    </ul>
    {% if perms.sitio.add_articulo %}
    <a href="{% url 'sitio:articulo_alta'%}">Dar de alta un Producto</a>
    <br>
    <br>
    <h3>Agragados al Carrito</h3>
    <ul>
        {% for articulo in leer_mas_tarde %}
            <li>{{articulo}}</li>
        {% empty %}
            <li>No hay productos para ver mas tarde.</li>
        {% endfor %}
    </ul>
    {% endif %}
{% endblock %}

YAGUARETE_KAA_SA/sitio/templates/eCommerce/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <title>JAGUARETE KAA S.A.</title>
        <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <link rel="stylesheet" href="{% static 'estilos.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
        <script src="{% static 'scripts.js' %}"></script>
    </head>
    <header id="encabezado">
        <br>
        <h1><img src="static\images\logoempresa.png" id="Logo_Empresa" style="width:80px;height:70px;">  YAGUARETE KAA S.A.</img></h1>
        <div style="float: right">
            <div id="usuario" class="navbar navbar-expand-lg navbar-light bg-light">
                <div id="bloque_usuario">
                    {% if user.is_authenticated %}
                        Estas conectado como: {{ user.get_username }} <a role="button" class="btn btn-outline-warning btn-sm" href="{% url 'logout'%}?next={{request.path}}">Salir</a>
                    {% else %}                  
                        <a role="button" class="btn btn-outline-success btn-sm" href="{% url 'login'%}?next={{request.path}}">LOGIN</a>
                    {% endif %} 
                </div>
                <div id="bloque_usuario">
                    {% if user.is_authenticated %}
                    {% else %}  
                        <a role="button" class="btn btn-outline-success btn-sm" href="eCommerce/registro.html">REGISTRO</a>
                    {% endif %} 
                </div>
                <div id="bloque_carrito">
                    {% if user.is_authenticated %}
                    {% else %} 
                    <a role="button" class="btn btn-outline-success btn-sm" href="{% url 'sitio:carrito' %}">CARRITO</a>
                    {% endif %} 
                </div>

            </div>
        </div>
    </header>
    <nav>
        <div>
            <nav id="menu_principal" class="navbar navbar-expand-lg navbar-light bg-light">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'sitio:index' %}">
                            HOME
                        </a>
                        
                    </li>
                    <li class="nav-item">
                        <div class="dropdown">
                            <a type="button" class="nav-link dropdown-toggle" data-toggle="dropdown">
                            CATEGORIAS
                            </a>
                            <div class="dropdown-menu">
                                {% for seccion in lista_secciones %}
                                    <a class="dropdown-item" href="{% url 'sitio:filtro_secciones' seccion.id%}">{{ seccion }}</a>
                                {% endfor %}
                            </div>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'sitio:pantallaDeAcercaDe' %}">
                            ACERCA DE...
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href='mailto:contacto@yaguaretekaasa.com'>
                            CONTACTO
                        </a>
                    </li>
                    <li class="nav-item">
                        {% if user.is_authenticated %}

                        <a class="nav-link" href="{% url 'sitio:articulo_alta' %}">
                            NUEVO PRODUCTO
                        </a>
                    
                        {% else %} 

                        {% endif %} 

                    </li>
                    <li class="nav-item">
                        <input type="text" placeholder="BUSCAR">
                        <a class="nav-link" href="{% url 'sitio:resultadoDeBusqueda' %}">
                            <img src="static\images\lupa.png" style="text-align: center"></imp>
                        </a>
                    </li>
                <ul>
            </nav>
        </div> 
    </nav>
    <body>
            {% block content %}
            {% endblock %}
        </div>
    </body>
    <footer style="background-color: rgb(191, 194, 33); text-align: center;">
        <p>YAGUARETE KAA S.A. </p>
        <P>Desarrollador: Fernando Molina</P>
        <p>All rights reserved Todos los derechos reservados</p>
   </footer>
</html>

YAGUARETE_KAA_SA/sitio/templates/eCommerce/producto.html
{% extends "eCommerce/layout.html" %}
{% block content %}
<h2>{{ producto.nombre }}</h2>
<div class="alert alert-info" role="alert"></div>
<div class="alert alert-info" role="alert">{{ producto.categoria }}</div>
<p><span class="precio" >{{ producto.precio }}</span></p>
<a href="{% url 'sitio:ver_mas_tarde' producto.id %}">Ver Mas Tarde</a>
<p><img src="{{ media_url  }}{{ producto.imagen.url }}" alt="{{ producto.imagen.name }}" /></p>
<h3>Contenido:</h3>
<p id="contenido">{{ producto.contenido |safe }}</p>
<p>Publicado por <span class="badge badge-secondary">{{ producto.moderador }}</span></p>
<a href="{% url 'sitio:index'%}">Volver</a>
{% endblock %}

YAGUARETE_KAA_SA/sitio/templates/eCommerce/producto_edicion.html
{% extends "eCommerce/layout.html" %}
{% block content %}
<h3>Editar un Producto</h3>
<div class="alert alert-info" role="alert"></div>
<form enctype="multipart/form-data" action="{% url 'sitio:producto_editar' producto.id %}" method="post" >
    {% csrf_token %}
    <div class="form-group row">
        <label for="categoria_input"  class="col-sm-2 col-form-label">Categoria:</label> {{ form.categoria }} {{ form.categoria.errors }}
    </div>
    <div class="form-group row">
        <label for="nombre_input"  class="col-sm-2 col-form-label">Nombre:</label> {{ form.nombre }} {{ form.nombre.errors }}
    </div>
    <div class="form-group row">
        <label for="precio_input"  class="col-sm-2 col-form-label">Precio:</label> {{ form.precio }} {{ form.precio.errors }}
    </div>
    <div class="form-group row">
        <label for="imagen_input"  class="col-sm-2 col-form-label">Imagen Adjunta:</label> {{ form.imagen }} {{ form.imagen.errors }}
    </div>
    <div class="form-group row"  class="col-sm-2 col-form-label">
        <label for="contenido_input">Contenido:</label> {{ form.contenido }} {{ form.contenido.errors }}
        <script>$("#id_contenido").removeAttr("required");</script>
    </div>
    <div class="col-auto">
        <a class="btn btn-secondary" href="{% url 'sitio:index'%}">Volver</a>
        <input type="submit" class="btn btn-primary" value="Editar">
    </div>
</form>
<a href="{% url 'sitio:index'%}">Volver</a>
{% endblock %}

YAGUARETE_KAA_SA/sitio/templates/eCommerce/producto_nuevo.html
{% extends "eCommerce/layout.html" %}
{% block content %}
<h3>Dar de Alta un Producto</h3>
<div class="alert alert-info" role="alert"></div>
<form enctype="multipart/form-data" action="{% url 'sitio:producto_alta' %}" method="post" >
    {% csrf_token %}
    <div class="form-group row">
        <label for="seccion_input"  class="col-sm-2 col-form-label">Categoria:</label> {{ form.categoria }} {{ form.categoria.errors }}
    </div>
    <div class="form-group row">
        <label for="titulo_input"  class="col-sm-2 col-form-label">Nombre:</label> {{ form.nombre }} {{ form.nombre.errors }}
    </div>
    <div class="form-group row">
        <label for="precio_input"  class="col-sm-2 col-form-label">Precio:</label> {{ form.precio }} {{ form.precio.errors }}
    </div>
    <div class="form-group row">
        <label for="imagen_input"  class="col-sm-2 col-form-label">Imagen Adjunta:</label> {{ form.imagen }} {{ form.imagen.errors }}
    </div>
    <div class="form-group row"  class="col-sm-2 col-form-label">
        <label for="contenido_input">Contenido:</label><br> {{ form.contenido }} {{ form.contenido.errors }}
        <script>$("#id_contenido").removeAttr("required");</script>
    </div>
    <div class="col-auto">
        <a class="btn btn-secondary" type="button" href="{% url 'sitio:index'%}">Volver</a>
        <input type="submit" class="btn btn-primary" value="Grabar">
    </div>
</form>

{% endblock %}

YAGUARETE_KAA_SA/sitio/templates/eCommerce/registro.html
{% extends "registration/layout.html" %}

{% block content %}

  <h2>Formulario de Registro</h2>
  <form method="post" action="{% url 'registro' %}">
    {% csrf_token %}
    {% for campo in form %}
      <p>
        {{ campo.label_tag }}<br>
        {{ campo }}
        {% if campo.help_text %}
          <small style="color: grey">{{ campo.help_text }}</small>
        {% endif %}
        {% for error in campo.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Confirmar Registro</button>
  </form>
  
{% endblock %}